[workspace]
members = [
    "kernel",
    "apps/dali-app-hello",
    "crates/dali-usb",
    "crates/dali-amrn",
    "crates/dali-device",
    "crates/dali-sdk",
    "crates/dali-cli",
    "crates/dali-targets",
]
resolver = "2"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"

[workspace.lints.clippy]
all = "warn"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
