[package]
name = "dali-kernel"
version = "0.1.0-alpha.1"
edition = "2024"
publish = false

[features]
default = ["board-stm32f405-sd", "usb-cdc"]
sdio = [
    "stm32f4xx-hal/sdio",
    "stm32f4xx-hal/sdio-host",
    "stm32f4xx-hal/stm32f405",
]
board-stm32f405-sd = ["sdio"]
log-colors = []
usb-cdc = ["stm32f4xx-hal/otg-fs", "stm32f4xx-hal/usb_fs", "dep:usb-device", "dep:usbd-serial"]
abi-current = []
abi-mpu = ["abi-current"]
abi-context-switch = ["abi-mpu"]
abi-relocation = ["abi-mpu"]
abi-test-fixtures = ["abi-mpu"]
abi-authentication = ["abi-relocation", "dep:dali-crypto"]
repository-loader = ["abi-authentication", "dep:dali-metadata"]
storage-write = []
storage-interruption-test = ["storage-write"]

[lints]
workspace = true

[dependencies]
dali-amrn = { path = "../crates/dali-amrn" }
dali-crypto = { path = "../crates/dali-crypto", optional = true }
dali-metadata = { path = "../crates/dali-metadata", optional = true }
dali = { path = "../crates/dali-sdk" }
dali-usb = { path = "../crates/dali-usb" }
dali-targets = { path = "../crates/dali-targets" }
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-sdmmc = { version = "=0.10.0", default-features = false }
fugit = "=0.3.9"
stm32f4xx-hal = { version = "0.20", default-features = false }
panic-halt = "1.0"
rtt-target = "0.6"
usb-device = { version = "=0.3.2", optional = true }
usbd-serial = { version = "=0.2.2", optional = true }

[build-dependencies]
dali-targets = { path = "../crates/dali-targets" }

[[bin]]
name = "dali-kernel"
path = "src/main.rs"
harness = false

[lib]
name = "dali_kernel_core"
path = "src/lib.rs"
