[package]
name = "dali-kernel"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = ["board-blackpill-f411", "usb-cdc"]
board-blackpill-f411 = ["stm32f4xx-hal/stm32f411"]
sdio = [
    "stm32f4xx-hal/sdio",
    "stm32f4xx-hal/sdio-host",
    "stm32f4xx-hal/stm32f405",
]
board-stm32f405-sd = ["sdio"]
log-colors = []
usb-cdc = ["stm32f4xx-hal/otg-fs", "stm32f4xx-hal/usb_fs", "dep:usb-device", "dep:usbd-serial"]

[lints]
workspace = true

[dependencies]
dali-amrn = { path = "../crates/dali-amrn" }
dali-usb = { path = "../crates/dali-usb" }
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-sdmmc = { version = "=0.10.0", default-features = false }
stm32f4xx-hal = { version = "0.20", default-features = false }
panic-halt = "1.0"
rtt-target = "0.6"
usb-device = { version = "=0.3.2", optional = true }
usbd-serial = { version = "=0.2.2", optional = true }

[[bin]]
name = "dali-kernel"
path = "src/main.rs"
harness = false
