[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x"
]

[alias]
check-kernel = "check -p dali-kernel --target thumbv7em-none-eabihf"
build-kernel = "build -p dali-kernel --target thumbv7em-none-eabihf"
