[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x"
]

[alias]
check-kernel = "check -p dali-firmware --bin dali-f405 --no-default-features --features stm32f405 --target thumbv7em-none-eabihf"
build-kernel = "build -p dali-firmware --bin dali-f405 --no-default-features --features stm32f405 --target thumbv7em-none-eabihf"
