[package]
name = "dali-app-fault-bus"
version = "0.1.0-alpha.2"
edition = "2024"
publish = false

[workspace]

[dependencies]
dali_sdk = { package = "dali", path = "../../crates/dali-sdk", features = ["abi-current"] }
dali-targets = { path = "../../crates/dali-targets" }

[build-dependencies]
dali-targets = { path = "../../crates/dali-targets" }

[features]
embedded-payload = []
abi-current = ["dali_sdk/abi-current"]

[lib]
path = "src/lib.rs"

[[bin]]
name = "dali-app-fault-bus"
path = "src/main.rs"
required-features = ["embedded-payload"]
test = false
