[package]
name = "dali-cli"
version = "0.1.0-alpha.1"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
dali-amrn = { path = "../dali-amrn" }
dali-device = { path = "../dali-device" }
dali-targets = { path = "../dali-targets" }
object = { version = "0.40", default-features = false, features = ["read", "elf"] }

[[bin]]
name = "dali"
path = "src/main.rs"
