[package]
name = "dali-app-hello"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
dali-sdk = { path = "../../crates/dali-sdk" }

[features]
embedded-payload = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "dali-app-hello"
path = "src/main.rs"
required-features = ["embedded-payload"]
test = false

[lints]
workspace = true
