[package]
name = "dali-kernel-api"
version = "0.1.0-alpha.2"
edition = "2024"
publish = true
description = "Public hardware-neutral API for Dali OS kernel integrations"
license = "MIT OR Apache-2.0"

[features]
storage-write = []

[dependencies]
dali-driver-api = { path = "../dali-driver-api" }
dali-targets = { path = "../dali-targets" }

[lints]
workspace = true
