[application]
name = "dali-app-fault-psp"
version = "0.1.0"
sdk = "dali"

[build]
target_profile = "f405"
abi_version = 3
format_version = 4
package_id = "102030405060708090A0B0C0D0E0F000"
minimum_kernel_version = "0.1.0"
required_services = "0x1"
slot = "slot0"
profile = "dev"
entry_symbol = "amiran_entry"
entry_offset = 0
